services:
  - type: web
    name: oncoderma-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEBUG
        value: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        fromService:
          type: web
          name: oncoderma-api
          property: port
      - key: CORS_ORIGINS
        value: '["https://oncoderma.vercel.app","https://oncoderma.netlify.app"]'
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: '["oncoderma-api.onrender.com"]'
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: '["image/jpeg","image/jpg","image/png"]'
      - key: UPLOAD_DIR
        value: /tmp/oncoderma_uploads
      - key: PROCESSING_TIME_MIN
        value: 2
      - key: PROCESSING_TIME_MAX
        value: 8
    healthCheckPath: /health
    autoDeploy: true
