services:
  - type: web
    name: oncoderma-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: '["https://oncoderma.vercel.app","https://oncoderma-frontend.netlify.app"]'
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: PROCESSING_TIME_MIN
        value: 2
      - key: PROCESSING_TIME_MAX
        value: 8
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_DIR
        value: /tmp/oncoderma_uploads